<?xml version="1.0" encoding="utf-8"?><Database Name="E-Comerce" Class="Data_ShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DTTHO;Initial Catalog=E-Comerce;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="E_ComerceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CartID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Account_UserInformation" Member="UserInformation" ThisKey="UserID" OtherKey="UserID" Type="UserInformation" Cardinality="One" />
      <Association Name="ShoppingCart_Account" Member="ShoppingCart" ThisKey="CartID" OtherKey="CartID" Type="ShoppingCart" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInformation" Member="UserInformations">
    <Type Name="UserInformation">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HomeAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WorkAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="UserInformation_Receipt" Member="Receipts" ThisKey="UserID" OtherKey="UserID" Type="Receipt" />
      <Association Name="Account_UserInformation" Member="Account" ThisKey="UserID" OtherKey="UserID" Type="Account" IsForeignKey="true" />
      <Association Name="AccountPaymentInfo_UserInformation" Member="AccountPaymentInfo" ThisKey="UserID" OtherKey="UserID" Type="AccountPaymentInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccountPaymentInfo" Member="AccountPaymentInfos">
    <Type Name="AccountPaymentInfo">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreditCardNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CCV" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NameOnCard" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AccountPaymentInfo_UserInformation" Member="UserInformation" ThisKey="UserID" OtherKey="UserID" Type="UserInformation" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="Products" ThisKey="CategoryID" OtherKey="CategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Image_product" Member="Image_products">
    <Type Name="Image_product">
      <Column Name="ProductID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MappingCartProduct" Member="MappingCartProducts">
    <Type Name="MappingCartProduct">
      <Column Name="CartID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Product_MappingCartProduct" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
      <Association Name="ShoppingCart_MappingCartProduct" Member="ShoppingCart" ThisKey="CartID" OtherKey="CartID" Type="ShoppingCart" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MappingReceiptProduct" Member="MappingReceiptProducts">
    <Type Name="MappingReceiptProduct">
      <Column Name="ReceiptID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Product_MappingReceiptProduct" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
      <Association Name="Receipt_MappingReceiptProduct" Member="Receipt" ThisKey="ReceiptID" OtherKey="ReceiptID" Type="Receipt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProductDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProductPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CurrentQuantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Images" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Product_MappingCartProduct" Member="MappingCartProducts" ThisKey="ProductID" OtherKey="ProductID" Type="MappingCartProduct" />
      <Association Name="Product_MappingReceiptProduct" Member="MappingReceiptProducts" ThisKey="ProductID" OtherKey="ProductID" Type="MappingReceiptProduct" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Receipt" Member="Receipts">
    <Type Name="Receipt">
      <Column Name="ReceiptID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Receipt_MappingReceiptProduct" Member="MappingReceiptProducts" ThisKey="ReceiptID" OtherKey="ReceiptID" Type="MappingReceiptProduct" />
      <Association Name="UserInformation_Receipt" Member="UserInformation" ThisKey="UserID" OtherKey="UserID" Type="UserInformation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingCart" Member="ShoppingCarts">
    <Type Name="ShoppingCart">
      <Column Name="CartID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingCart_Account" Member="Accounts" ThisKey="CartID" OtherKey="CartID" Type="Account" />
      <Association Name="ShoppingCart_MappingCartProduct" Member="MappingCartProducts" ThisKey="CartID" OtherKey="CartID" Type="MappingCartProduct" />
    </Type>
  </Table>
</Database>